---
title: "Stats 2 Project 1"
author: "Kito Patterson <br />  Andy Heroy <br /> Ryan Quincy Paul "
date: "2/7/2019"
output: html_document
---



###Load / View Data
```{r}
#setwd("C:/Users/andyh/Google Drive/Education/SMU/Courses/DS_6372_Applied_Statistics/project 1/Project")

df <- read.csv("datasets/lego_sets.csv")

```

###Remove description columns and check datatypes
```{r echo=TRUE}
legos <- df[ -c(6,8)]
#remove blanks from play star rating
legos <- legos[(legos$review_difficulty!= "" & legos$play_star_rating!= ""),]

str(legos)



```


###Exploratory Analysis
```{r EDAGraphs_and_such, fig.height=4}
mysummary<-function(x){
  result<-c(length(x),mean(x),sd(x),sd(x)/sqrt(length(x)))
  names(result)<-c("N","Mean","SD","SE")
  return(result)
}

sumstats<-aggregate(play_star_rating~ages*review_difficulty,data=legos,mysummary)
sumstats<-cbind(sumstats[,1:2],sumstats[,-(1:2)])
sumstats

pairs(legos[-c(1,6:8,10,12)])

library(ggplot2)
ggplot(sumstats,aes(x=review_difficulty,y=Mean,group=ages,colour=ages))+
  ylab("Play Star Rating")+
  geom_line()+
  geom_point()+
  geom_point()+
  geom_errorbar(aes(ymin=Mean-SE,ymax=Mean+SE),width=.1)

```

``` {r Test Code}


# 
# par(mfrow=c(1,2))
# plot(review_difficulty,play_star_rating, xlab="Review Difficulty",ylab="Play Rating")
# new<-data.frame(review_difficulty=seq(30,300,.1))
# lines(seq(30,300,.1),predict(lm(play_star_rating~review_difficulty),newdata=new),col="red",lwd=4)
# 
# plot(as.factor(review_difficulty), play_star_rating,xlab="Review difficulty",ylab="Play Rating",title="Auto Data Set",col=c(7,32,57,82,107))


```
